/* eslint-disable */
// This file was generated by script
// this file is used to generate icon names from files within this directory
// icons are used in Icon component

import email from './email.svg';
import socialX from './social-x.svg';

const icons = {
email,
socialX,
};

export default icons;
